#!/bin/sh
#Init script to load and unload misc-modules and scull

case "$1" in 
	start)
	  echo "Loading"
	  start-stop-daemon -S -n module_load -a /usr/bin/module_load -- faulty
	  start-stop-daemon -S -n scull_load -a /usr/bin/scull_load 
	  /usr/bin/aesdchar_load 
	  modprobe hello
	  ;;
	  
	stop)
	  echo "Unloading"
	  start-stop-daemon -S -n module_unload -a /usr/bin/module_unload -- faulty
	  start-stop-daemon -S -n scull_unload -a /usr/bin/scull_unload 
	  /usr/bin/aesdchar_unload 
	  rmmod hello
	  ;;
	*)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
